ifeq ($(OS),Windows_NT)
HOME = C:/Users/$(USERNAME)
endif
PANSTYLES= $(HOME)/.pandoc
MISC= $(PANSTYLES)/pandoc_misc
include $(MISC)/Makefile.in
include $(MISC)/Makefile

## userland: uncomment and replace
# MDDIR:= markdown
# DATADIR:= data
# TARGETDIR:= Out
# IMAGEDIR:= images
# WAVEDIR:= waves
# BITDIR:= bitfields
# BIT16DIR:= bitfield16

# CONFIG:= config.yaml
# INPUT:= TITLE.md
TARGET:= USB4x3HUB
##
