---
title: 【改訂】 USB4x3HUBの本
abstract: Windows/Mac/XBOX/PS4でキーボードとマウス（ともう一つ）を切り替えて共有できる基板
circle: KY技研
author: "@_K4ZUKI_"
comiket: "C92"
year: "2017"
publisher: キンコーズオンラインで印刷製本
docrevision: "2.0"
front: images/USB4x3HUB-block.png
...
